DROP SCHEMA IF EXISTS MUSIC;
CREATE SCHEMA MUSIC;

DROP TABLE IF EXISTS MUSIC.USER_MODEL;
DROP TABLE IF EXISTS MUSIC.AUTOR;
DROP TABLE IF EXISTS MUSIC.ALBUM;

CREATE TABLE MUSIC.USER_MODEL (
  ID INT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE MUSIC.AUTOR (
  ID INT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL
);
  
  CREATE TABLE MUSIC.ALBUM (
  ID INT PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL,
  AUTOR_ID INT NOT NULL,
  IMAGEM VARCHAR(250)
);

 ALTER TABLE MUSIC.ALBUM
    ADD FOREIGN KEY (AUTOR_ID) 
    REFERENCES AUTOR(ID);