name: Example java build and deploy

on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_CONTAINER_REGISTRY: registry-precision.ddns.net

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Build Docker Project and pusing to registry
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:latest
          docker push ${{ env.DOCKER_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:latest